// src/app/features/profile/components/follow-button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  EventEmitter,
  inject,
  Input,
  Output,
  signal,
} from '@angular/core';
import { Router } from '@angular/router';
import { switchMap } from 'rxjs/operators';
import { EMPTY } from 'rxjs';
import { ProfileService } from '../services/profile.service';
import { UserService } from '../../../core/auth/services/user.service';
import { Profile } from '../models/profile.model';
import { NgClass } from '@angular/common';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-follow-button',
  template: `
    <button
      class="btn btn-sm action-btn"
      [ngClass]="{
        disabled: isSubmitting(),
        'btn-outline-secondary': !profile.following,
        'btn-secondary': profile.following,
      }"
      (click)="toggleFollowing()"
    >
      <i class="ion-plus-round"></i>
      &nbsp;
      {{ profile.following ? 'Unfollow' : 'Follow' }} {{ profile.username }}
    </button>
  `,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FollowButtonComponent {
  @Input() profile!: Profile;
  @Output() followToggle = new EventEmitter<Profile>();
  isSubmitting = signal(false);
  destroyRef = inject(DestroyRef);

  constructor(
    private readonly profileService: ProfileService,
    private readonly router: Router,
    private readonly userService: UserService,
  ) {}

  toggleFollowing(): void {
    this.isSubmitting.set(true);

    this.userService.isAuthenticated
      .pipe(
        switchMap((isAuthenticated: boolean) => {
          if (!isAuthenticated) {
            void this.router.navigate(['/login']);
            return EMPTY;
          }

          if (this.profile.following) {
            return this.profileService.unfollow(this.profile.username);
          } else {
            return this.profileService.follow(this.profile.username);
          }
        }),
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe({
        next: profile => {
          this.isSubmitting.set(false);
          this.followToggle.emit(profile);
        },
        error: () => {
          this.isSubmitting.set(false);
        },
      });
  }
}

// react-app/src/features/profile/components/FollowButton.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useUser } from '../../../core/auth/services/user.service';
import { ProfileService } from '../services/profile.service';
import type { Profile } from '../models/profile.model';

interface FollowButtonProps {
  profile: Profile;
  onToggle: (profile: Profile) => void;
}

export function FollowButton({ profile, onToggle }: FollowButtonProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { isAuthenticated } = useUser();
  const navigate = useNavigate();

  const toggleFollowing = async () => {
    setIsSubmitting(true);

    if (!isAuthenticated) {
      navigate('/login');
      return;
    }

    try {
      const updatedProfile = profile.following
        ? await ProfileService.unfollow(profile.username)
        : await ProfileService.follow(profile.username);
      setIsSubmitting(false);
      onToggle(updatedProfile);
    } catch {
      setIsSubmitting(false);
    }
  };

  return (
    <button
      className={`btn btn-sm action-btn ${isSubmitting ? 'disabled' : ''} ${
        profile.following ? 'btn-secondary' : 'btn-outline-secondary'
      }`}
      onClick={toggleFollowing}
    >
      <i className="ion-plus-round"></i>
      &nbsp;
      {profile.following ? 'Unfollow' : 'Follow'} {profile.username}
    </button>
  );
}
