// src/app/features/article/components/article-list.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  EventEmitter,
  inject,
  Input,
  OnChanges,
  Output,
  signal,
  SimpleChanges,
} from '@angular/core';
import { ArticlesService } from '../services/articles.service';
import { ArticleListConfig } from '../models/article-list-config.model';
import { Article } from '../models/article.model';
import { ArticlePreviewComponent } from './article-preview.component';
import { NgClass } from '@angular/common';
import { RouterLink } from '@angular/router';
import { LoadingState } from '../../../core/models/loading-state.model';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-article-list',
  template: `
    @if (loading() === LoadingState.LOADING) {
      <div class="article-preview">Loading articles...</div>
    }

    @if (loading() === LoadingState.LOADED) {
      @for (article of results(); track article.slug) {
        <app-article-preview [articleInput]="article" />
      } @empty {
        <div class="article-preview empty-feed-message">
          @if (isFollowingFeed) {
            Your feed is empty. Follow some users to see their articles here, or check out the
            <a routerLink="/">Global Feed</a>!
          } @else {
            No articles are here... yet.
          }
        </div>
      }

      <nav>
        <ul class="pagination">
          @for (pageNumber of totalPages(); track pageNumber) {
            <li class="page-item" [ngClass]="{ active: pageNumber === page() }">
              <button class="page-link" (click)="setPageTo(pageNumber)">
                {{ pageNumber }}
              </button>
            </li>
          }
        </ul>
      </nav>
    }
  `,
  imports: [ArticlePreviewComponent, NgClass, RouterLink],
  styles: `
    .page-link {
      cursor: pointer;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ArticleListComponent implements OnChanges {
  query!: ArticleListConfig;
  results = signal<Article[]>([]);
  page = signal(1);
  totalPages = signal<number[]>([]);
  loading = signal(LoadingState.NOT_LOADED);
  LoadingState = LoadingState;
  destroyRef = inject(DestroyRef);

  @Input() limit!: number;
  @Input() config!: ArticleListConfig;
  @Input() currentPage = 1;
  @Input() isFollowingFeed = false;
  @Output() pageChange = new EventEmitter<number>();

  ngOnChanges(changes: SimpleChanges): void {
    const configChange = changes['config'];
    const pageChange = changes['currentPage'];

    if (configChange?.currentValue) {
      this.query = configChange.currentValue;
      // Only reset page if currentPage wasn't also provided in this change
      if (!pageChange?.currentValue) {
        this.page.set(1);
      }
    }

    if (pageChange?.currentValue) {
      this.page.set(pageChange.currentValue);
    }

    // Run query if we have a config and either config or page changed
    if (this.query && (configChange || pageChange)) {
      this.runQuery();
    }
  }

  constructor(private readonly articlesService: ArticlesService) {}

  setPageTo(pageNumber: number) {
    if (pageNumber !== this.page()) {
      this.page.set(pageNumber);
      this.pageChange.emit(pageNumber);
      this.runQuery();
    }
  }

  runQuery() {
    this.loading.set(LoadingState.LOADING);
    this.results.set([]);

    // Create limit and offset filter (if necessary)
    if (this.limit) {
      this.query.filters.limit = this.limit;
      this.query.filters.offset = this.limit * (this.page() - 1);
    }

    this.articlesService
      .query(this.query)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(data => {
        this.loading.set(LoadingState.LOADED);
        this.results.set(data.articles);

        // Used from http://www.jstips.co/en/create-range-0...n-easily-using-one-line/
        this.totalPages.set(
          Array.from(new Array(Math.ceil(data.articlesCount / this.limit)), (val, index) => index + 1),
        );
      });
  }
}

// src/features/article/components/article-list.tsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArticleListConfig } from '../models/article-list-config';
import { Article } from '../models/article';
import { ArticlePreview } from './article-preview';
import { LoadingState } from '../../../core/models/loading-state';
import * as articlesService from '../services/articles.service';

export function ArticleList({
  limit,
  config,
  currentPage = 1,
  isFollowingFeed = false,
  onPageChange,
}: {
  limit: number;
  config: ArticleListConfig;
  currentPage?: number;
  isFollowingFeed?: boolean;
  onPageChange?: (page: number) => void;
}) {
  const controlled = onPageChange != null;
  const [internalPage, setInternalPage] = useState(1);
  const page = controlled ? currentPage || 1 : internalPage;

  const [results, setResults] = useState<Article[]>([]);
  const [totalPages, setTotalPages] = useState<number[]>([]);
  const [loading, setLoading] = useState<LoadingState>(LoadingState.NOT_LOADED);

  useEffect(() => {
    let active = true;
    setLoading(LoadingState.LOADING);
    setResults([]);

    const query: ArticleListConfig = { ...config, filters: { ...config.filters } };
    if (limit) {
      query.filters.limit = limit;
      query.filters.offset = limit * (page - 1);
    }

    articlesService
      .query(query)
      .then(data => {
        if (!active) {
          return;
        }
        setLoading(LoadingState.LOADED);
        setResults(data.articles);
        setTotalPages(Array.from(new Array(Math.ceil(data.articlesCount / limit)), (_, index) => index + 1));
      })
      .catch(() => {
        if (active) {
          setLoading(LoadingState.LOADED);
        }
      });

    return () => {
      active = false;
    };
  }, [config, page, limit]);

  const setPageTo = (pageNumber: number) => {
    if (pageNumber !== page) {
      if (controlled) {
        onPageChange?.(pageNumber);
      } else {
        setInternalPage(pageNumber);
      }
    }
  };

  return (
    <>
      {loading === LoadingState.LOADING && <div className="article-preview">Loading articles...</div>}

      {loading === LoadingState.LOADED && (
        <>
          {results.length > 0 ? (
            results.map(article => <ArticlePreview key={article.slug} article={article} />)
          ) : (
            <div className="article-preview empty-feed-message">
              {isFollowingFeed ? (
                <>
                  Your feed is empty. Follow some users to see their articles here, or check out the{' '}
                  <Link to="/">Global Feed</Link>!
                </>
              ) : (
                'No articles are here... yet.'
              )}
            </div>
          )}

          <nav>
            <ul className="pagination">
              {totalPages.map(pageNumber => (
                <li key={pageNumber} className={'page-item' + (pageNumber === page ? ' active' : '')}>
                  <button className="page-link" onClick={() => setPageTo(pageNumber)}>
                    {pageNumber}
                  </button>
                </li>
              ))}
            </ul>
          </nav>
        </>
      )}
    </>
  );
}
